# Layer overview:
#
#   [main]
#   [altgr]
#   [extend]
#   [extend2]
#   [altgr+extend2]
#   [disable_oneshot_mods]

[global]
oneshot_timeout = 600

[ids]
# Apply this configuration to all connected keyboards
*

# Include your layouts (caws for now)
include layouts/iso/colemak-dh-caws-iso

[main]

# Hold capslock -> extend layer
capslock = layer(extend)

# Set your custom sticky keys (oneshot mods)
rightalt   = oneshot(altgr)
leftshift  = oneshot(shift)
rightshift = oneshot(shift)

[altgr]
# AltGr + capslock -> extend2 layer
capslock = layer(extend2)

# (may not be neccesary, just in case)
altgr = noop

[extend]
include extend/iso/extend-caws-iso

[extend2]
# The oneshot(altgr) is consumed by the first keypress (capslock), leaving
# altgr deactivated while extend2 remains active for as long as capslock
# is held.
include extend/iso/extend2-caws-iso

[altgr+extend2]
# This layer is active when both altgr and extend2 are simultaneously active.
# It prevents the G modifier from [altgr] from leaking into extend2 outputs.
# Without it, we would get G-S-1 instead of just S-1.
include extend/iso/extend2-caws-iso

# We can disable our oneshot mods in the extend2 layer, useful for gaming
f11 = clear()
f12 = toggle(disable_oneshot_shifts)

[disable_oneshot_shifts]
# Toggled using f12, see above
leftshift  = leftshift
rightshift = rightshift
# rightalt = rightalt




# Our personal overrides must come last
include custom/es_overrides
